openapi: 3.0.0
info:
  title: Medicine Management API
  description: 의약품 관리 및 사용자 인증 API
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: 개발 서버

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        password:
          type: string
        birth_date:
          type: string
          format: date
          
    Medicine:
      type: object
      properties:
        id:
          type: string
          format: uuid
        medi_name:
          type: string
        company_name:
          type: string
        buying_date:
          type: string
          format: date
        exp_date:
          type: string
          format: date
        main_symptom:
          type: string
        memo:
          type: string
        notification:
          type: boolean
        user_id:
          type: string
          format: uuid

    Error:
      type: object
      properties:
        msg:
          type: string
        error:
          type: string

paths:
  /auth/register:
    post:
      tags:
        - 인증
      summary: 회원가입
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - birth_date
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                birth_date:
                  type: string
                  format: date
      responses:
        '200':
          description: 회원가입 성공/실패 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      tags:
        - 인증
      summary: 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '201':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  msg:
                    type: string
        '200':
          description: 로그인 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/emailVerification:
    post:
      tags:
        - 인증
      summary: 이메일 인증
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: 인증 코드 발송 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  verificationCode:
                    type: string
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/find_pwd:
    post:
      tags:
        - 인증
      summary: 비밀번호 찾기
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: 비밀번호 재설정 이메일 발송 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: 사용자를 찾을 수 없음
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/reset_pwd:
    post:
      tags:
        - 인증
      summary: 비밀번호 재설정
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
              properties:
                token:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: 비밀번호 재설정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: 유효하지 않은 토큰
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/update_user/{id}:
    put:
      tags:
        - 인증
      summary: 회원정보 수정
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: 회원정보 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/delete_user/{id}:
    delete:
      tags:
        - 인증
      summary: 회원 탈퇴
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 회원 탈퇴 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '404':
          description: 회원정보가 없음
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /myPage/post_myMedi:
    post:
      tags:
        - 마이페이지
      summary: 나의 약품 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mediName
                - expDate
                - user_id
              properties:
                mediName:
                  type: string
                companyName:
                  type: string
                buyingDate:
                  type: string
                  format: date
                expDate:
                  type: string
                  format: date
                mainSymptom:
                  type: string
                memo:
                  type: string
                user_id:
                  type: string
                notification:
                  type: boolean
      responses:
        '201':
          description: 약품 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '400':
          description: 필수 입력값 누락
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /myPage/get_myMediList/{user_id}:
    get:
      tags:
        - 마이페이지
      summary: 나의 약품 목록 조회
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 약품 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Medicine'
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /myPage/delete_myMediList/{medicine_id}:
    delete:
      tags:
        - 마이페이지
      summary: 약품 삭제
      parameters:
        - in: path
          name: medicine_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 약품 삭제 성공
        '404':
          description: 약품을 찾을 수 없음
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /myPage/update_myMediList/{medicine_id}:
    put:
      tags:
        - 마이페이지
      summary: 나의 약품 정보 수정
      parameters:
        - in: path
          name: medicine_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Medicine'
      responses:
        '201':
          description: 약품 정보 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '400':
          description: 필수 입력값 누락
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /email/send-email:
    post:
      tags:
        - 이메일
      summary: 건의사항 이메일 전송
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - to
                - subject
                - text
                - category
              properties:
                to:
                  type: string
                  format: email
                subject:
                  type: string
                text:
                  type: string
                category:
                  type: string
      responses:
        '200':
          description: 이메일 전송 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /medicine/search:
    get:
      tags:
        - 의약품 정보
      summary: 의약품 검색
      parameters:
        - in: query
          name: term
          required: true
          schema:
            type: string
          description: 검색어
      responses:
        '200':
          description: 검색 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    효능:
                      type: string
                    제품명:
                      type: string
                    주성분:
                      type: string
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /medicine/info:
    get:
      tags:
        - 의약품 정보
      summary: 전체 의약품 정보 조회
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    효능:
                      type: string
                    제품명:
                      type: string
                    주성분:
                      type: string
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /medicine/info/{id}:
    get:
      tags:
        - 의약품 정보
      summary: 의약품 상세 정보 조회
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  효능:
                    type: string
                  제품명:
                    type: string
                  주성분:
                    type: string
        '404':
          description: 약품을 찾을 수 없음
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

tags:
  - name: 인증
    description: 회원가입/로그인/인증 관련 API
  - name: 마이페이지
    description: 개인 약품 관리 관련 API
  - name: 이메일
    description: 이메일 발송 관련 API
  - name: 의약품 정보
    description: 의약품 정보 조회 및 검색 관련 API